language: r
sudo: true
cache:
  packages: true
  directories:
  - _cache
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
    - libgdal1-dev
    - netcdf-bin
    - libproj-dev
    - libnetcdf-dev
    - netcdf-bin
    - libcurl4-openssl-dev
git:
  depth: 3
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update
- sudo add-apt-repository -y ppa:opencpu/jq
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libgeos-dev libjq-dev
  libnetcdf-dev libproj-dev libprotobuf-dev libudunits2-dev libv8-3.14-dev netcdf-bin
  protobuf-compiler libcurl4-openssl-dev
script:
- Rscript -e 'rmarkdown::render("wq.Rmd")'
- git config --global user.name "fawda123"
- git config --global user.email "mbafs2012@gmail.com"
- git add -A
- git commit -a -m "Updating wq rmd build for website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    - ben@ecoquants.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/tbep-tech.github.io
  - TRAVIS_BRANCH=master
  - secure: Tw20794PwlDfA4dUHWvkJ3jqy3f5uLIzyDjnZaDUPzWMdsyb1LdmgKS+o2PlOUhLI3OLrsIAzsqRBuR7mx6xOM/OysjsOQu/nA0VwpqAYaA2bvEgbPQgJ9JIHPfHt999ujAX2MhbN3Oj6jmLS0ZKTsxsb3LOV8AlLEpObOI0h9qaPmoe6ncb0sewH5T++GGAAap8K9PJxtPW+ypYGTHnXIKLyixxaLaa9+aKGI83WtJPJNEVRCES3SZKNG+OfjVU9ZXbIZUGmtGIsw5xN3eyA/6TgEyRRmOgC/KjA6rROMAeyd7QRKC2Hgbm2Vt5Uf10uX9pd4lVOozZfu2KkseEbpBlWkvVLbkrkFYBoilR/hbU7blM1U3Yuo+q9K6MdndsR48yw/SpkKbsOc6KfE0JN+bHGIsDHJaEbW14jCPiZrMW2ZhAqsUuu9IsFQDQUg4KDicch64/5u5DnO7710Y01q9/kibshfVuAp2wEs2lf3+nfK86r30Fcw4XvW/9o+K/8/bYdtwpBRk0O4BKe13yFYFV+KHlmEU/8dKP+XAr+PZAeQDWulTTF/k/frqSM4ehiSeFyHS+Ju5k2sxSa0gibFA94UGbkaNoevlZOLa6xo3cA3WJbpn08rjwTE8IF5Jj0Q6gA6Rb7iUdJupQ9aCaYEQEJaJIf4ROq7DUpXywaok=
