language: r
sudo: true
cache:
  packages: true
  directories:
  - _cache
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
    - libgdal1-dev
    - netcdf-bin
    - libproj-dev
    - libnetcdf-dev
    - netcdf-bin
git:
  depth: 3
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update
- sudo add-apt-repository -y ppa:opencpu/jq
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libgeos-dev libjq-dev
  libnetcdf-dev libproj-dev libprotobuf-dev libudunits2-dev libv8-3.14-dev netcdf-bin
  protobuf-compiler
script:
- Rscript -e 'rmarkdown::render("wq.Rmd")'
- git config --global user.name "fawda123"
- git config --global user.email "mbafs2012@gmail.com"
- git add -A
- git commit -a -m "Updating wq rmd build for website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    - ben@ecoquants.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/tbep-tech.github.io
  - TRAVIS_BRANCH=master
  - secure: JkWBG5hePgDqLRnevDz4Sg0qlvqofjFQPP1X8BoulKOpue8s5lK5syX5PmwuuAV8PhrBP3AbC46JJwILT3tqizrrBI8KNraPdO+d/jxtCE9z6X+b/xz3R8hnqW8s7HL+OKBmLZGPcdRnH+4S41tSDApm1j8rbALKA7nMKNiZMAjaciWaZvajkfkiAXkCWBEDgOOv4yoG4tfgOhNwZ0WeU8qYN88mpfyw67qptpBAYfMuEqZXnF1j3Q/FeRroGzCXMBHZO1Wf0jDfCAjn0vl9iZ5nRWtBbrRBuWMq7jRpOc34g2QfL+8AeVfJZaqM5pwS5sjf+pmGxYFVnjrMYdiXKZqMKi3eIXTVy97pF4wwDWDLU02K2GWK3aF8yq9/DziQd81gZVee53fRxrLhZRHFLSR/0JhTdoFRFM9Q572IBlU2NwSRpy5mP6MmN9fObStAfV1dZFw1bv1H/v9mKiKGaaG4l14sF6/d0sLblaBcaW/L1IjwNniq1sw5rFFG09nR8iI6q6I5gea7RbVZDn4XapKJ3ZrRaKWyQNAxC0IgcnveC7+6ZiX98FUAHpSY24A3DH+K7i3+BvawuqO1DO+BDCrO8kA+hrjwHojqlHh58ynGMmfH8YPHq1a1ksn/8Lepl3qpj/DdHm0H9cI5FebbTItAM8nPj4I5VTVx5oY+ZgA=
