language: r
sudo: false
cache:
  packages: true
  directories:
    - _cache
addons:
  apt:
    packages:
    - gdal-bin 
    - libgdal-dev 
    - libgdal1-dev 
    - netcdf-bin 
    - libproj-dev 
    - libnetcdf-dev 
    - netcdf-bin
git:
  depth: 3
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev libgeos-dev libjq-dev libnetcdf-dev libproj-dev libprotobuf-dev libudunits2-dev libv8-3.14-dev netcdf-bin protobuf-compiler
script:
  - Rscript -e 'knitr::knit("wq.Rmd", output = "wq.html")'
  - git config --global user.name "Marcus Beck (Travis-CI)"
  - git config --global user.email "mbafs2012@gmail.com"
  - git add -A
  - git commit -a -m "Updating wq rmd build for website via travis-ci.org [ci skip]"
  - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
env:
  global:
  - secure: "E8G0u19Fr1CrADUhZ7ZdKA7rLKH8bOEgsiDRQoGggvt3Qw11vh03jKY5MEi24OQTsgw4Lg3Ah+PZ8j5jwASmDk8RYw4VC19m54bdm+IKBRcAQNqH5d2RHJZnDWOkK+Sx3fTUV3ELsddKw9ye6mUwV+IRtPZuJTnYoePynOINbFDQYgHlO1PFLYD1FUmGMjewQqLy6eENGnlymepuj/w1eaqtKUdza2UT4izUBJpkjhayhD3sFMQToeyUV5+ee4JqCMvesBSff+v4iPBZ0Y29xNnlaHYMyy/+bYxqRRjHFwBk3pfTpg1Z35B/59Csf+SG0S+1dlNcoVZVeEnOj+cetxKgfD9vyIqZ2ky+MkF6LRysIn7QaDpbHn5tzA4yTfclIzW93BumQv2TSHfvH6/TTk8cPz6myP9HrLNFFtrHe22ERUlVrRpVw1+m6ja7TvEa4tBb25vBE4qrl6MSbZiMhE+Vu1oO6h6fOReLLQ1dT4kRC35ut9yJc22jrDLaHn7LiF3x5ZgUyaYfBUou5ywmAuvzY9b0gZA3nMt+JQisxgsp7xeZ3r+9HhIKrH/IApT7ZL5gPoLXiRv8+cZj8TOuGu63K40/nfE96Zp++GipubXbReDiOZjcIbxi00ts/VKcurY5vyUvLHb6CSGAKQYjB86Iyna4uxef2+stLBhDM+U="