language: r
sudo: false
cache: packages
git:
  depth: false

script:
- Rscript -e 'rmarkdown::render("index.Rmd")'
- git config --global user.name "fawda123"
- git config --global user.email "mbafs2012@gmail.com"
- git pull https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
- git add -A
- git commit -a -m "Updating index rmd build for website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/tbep-tech.github.io
  - TRAVIS_BRANCH=master
  - secure: Ds+YqGQRXl+9XnaKDSwCw2L+rpvn7Dw8e4mKUyNClbmvRi5rCZXCoFJ/PqDbRIcjz5/CRcNqMEOyPT/k/tQk7sNB3MpjEnt2jsZeweOJIeCpu5qYQ9qZKfVgS/AuwqVjwdzoi2TKidUZQnwKo0kFXm7ibfcKSKzTmmlt2P5rQBYVlRQFHBBiA9D7AyK71NKFnywWO+O0kXLHEArXViZW08xQ1VefkT+0RJjiWzvHkknHhmoKxlOtSBZkS88Xd4vsUx6JrWclzpqrWK1pNQw314QFYE+/Q3MT/YYxCYVXfQFmNgftE4qO2tdDiX8y4BBXzZAWI3SSXojlN+FsQIGhJAKzQ4n/znfthFxQhIYeqjdDaHEJwhsM+59GYp3BmALJkgktCArKU4BzTOwhQZKNL8McEsmAGOr5xHAyQ9dmLRPAHEdAZlA2JV82UQg+V74cJDirYsPz/Pw1QhSsM1dH/6H4oumuKhr84oiPqtvISCQRwm0WwByAqTkbatx+v1UoXB87L1fLIJWU+kwEweoG3wqUNHRfqzgXLUidU6gDJGJrF3Mh1zgzROaiErZCRXPke+3l6ounQqxcBWZuMSm/MCT55pQBm7aiI44LPvw4d5JMfEqZWl8UpPXkFYXb8RKDcMq0Qsc57BZSTzMAnvsBjrg0SNWyvax13CykIVqh5WU=
  - CRAN: http://cran.rstudio.com
